### PR TITLE
Add ChatGPT API

### LINKED ISSUE #89: Support new chat API (POST /chat/completions)
OpenAI announced support for a [new chat API](https://platform.openai.com/docs/api-reference/chat) like chatGPT. This has a similar request and response model to the completions endpoint but with slight variations.

POST: https://api.openai.com/v1/chat/completions

Request:
```json
{
  "model": "gpt-3.5-turbo",
  "messages": [{"role": "user", "content": "Hello!"}]
}

```

Response:
```json
{
  "id": "chatcmpl-123",
  "object": "chat.completion",
  "created": 1677652288,
  "choices": [{
    "index": 0,
    "message": {
      "role": "assistant",
      "content": "\n\nHello there, how may I assist you today?",
    },
    "finish_reason": "stop"
  }],
  "usage": {
    "prompt_tokens": 9,
    "completion_tokens": 12,
    "total_tokens": 21
  }
}
```

Further details can be found here: https://platform.openai.com/docs/guides/chat

### PR DESCRIPTION
**Pull request by sashabaranov**
Adds ChatGPT API. Fixes #89.

### CODE REVIEW

**Comment by lnashier** [comment]
I was thinking to send a PR. Within a minute saw this PR. :-)

**Comment by sashabaranov** [comment]
@lnashier duh, I should've chill instead of coding :D 

Your code review and any additions are really welcome. Tests, docs, etc.

**Comment by VarunMohan** [comment]
Is there a way we could also make this streaming?

**Comment by sashabaranov** [comment]
@VarunMohan done in #101, you can `go get -u github.com/sashabaranov/go-gpt3` to use that.

**Pull request merged**
