### PR TITLE
Configurable Transport

### PR DESCRIPTION
**Pull request by mwillfox**
Non-breaking changes which allow for a configurable "Transport" (language which was already used in the project, really a `*http.Client`).

This allows for setting a custom `RoundTripper` or using `github.com/hashicorp/go-retryablehttp`:

```go
transport := retryablehttp.NewClient().StandardClient()
c := gogpt.NewClientWithTransport(openAIAPIKey, transport)
```

With the recent stability issues and load of the OpenAI API this is necessary to use the module in a production environment.

### CODE REVIEW

**Comment by sashabaranov** [comment]
Hey, thank you for that PR! It made me think about how we want to approach client initialization — there was a great article about different ways of doing that, but I could not find it. The closest is this one: https://asankov.dev/blog/2022/01/29/different-ways-to-initialize-go-structs/

I don't think the usage of `.WithA().WithB().WithC()` chaining is a way forward for us here. I would rather prefer an API akin to:

```go
client := gogpt.NewClient()

// or

config := gogpt.DefaultConfig()
config.Transport = retryablehttp.NewClient().StandardClient()
client := gogpt.NewClientWithConfig(config)
```

@mwillfox would you have the bandwidth to do such a refactoring? It's totally cool if not — I can do it in a follow-up PR.

**Comment by mwillfox** [comment]
I should have time to refactor in the next few days and I'll update the PR. Thanks for the feedback!

**Comment by sashabaranov** [comment]
Will follow up this work in a `better-config` branch

**Review by Eriddle96 — COMMENTED** [review]
This is a great idea

**Pull request merged**
